try{
var OUT="/Users/leonardomeireles/Work/claude-roupa-de-jiu/webapp-jiu/.scratch/il-proto/gf-il.png";
var doc=app.documents.add(DocumentColorSpace.RGB, 760, 600);
var clay=new RGBColor();clay.red=198;clay.green=118;clay.blue=81; var ink=new RGBColor();ink.red=40;ink.green=44;ink.blue=54; var paper=new RGBColor();paper.red=243;paper.green=240;paper.blue=234;
var tq=doc.pathItems.add();tq.setEntirePath([[408.3,-488.1],[526,-461.5],[408.6,-374.3],[328.9,-372.5]]);tq.closed=true;tq.stroked=false;tq.filled=true;tq.fillColor=ink;
var l=doc.pathItems.add();l.setEntirePath([[499,-448.9],[475.7,-474.6]]);l.stroked=true;l.filled=false;l.strokeColor=ink;l.strokeWidth=34;l.strokeCap=StrokeCap.ROUNDENDCAP;l.strokeJoin=StrokeJoin.ROUNDENDJOIN;
var l=doc.pathItems.add();l.setEntirePath([[475.7,-474.6],[407,-437.7]]);l.stroked=true;l.filled=false;l.strokeColor=ink;l.strokeWidth=34;l.strokeCap=StrokeCap.ROUNDENDCAP;l.strokeJoin=StrokeJoin.ROUNDENDJOIN;
var l=doc.pathItems.add();l.setEntirePath([[475.7,-474.6],[408.3,-488.1]]);l.stroked=true;l.filled=false;l.strokeColor=ink;l.strokeWidth=34;l.strokeCap=StrokeCap.ROUNDENDCAP;l.strokeJoin=StrokeJoin.ROUNDENDJOIN;
var l=doc.pathItems.add();l.setEntirePath([[475.7,-474.6],[526,-461.5]]);l.stroked=true;l.filled=false;l.strokeColor=ink;l.strokeWidth=34;l.strokeCap=StrokeCap.ROUNDENDCAP;l.strokeJoin=StrokeJoin.ROUNDENDJOIN;
var l=doc.pathItems.add();l.setEntirePath([[408.3,-488.1],[306,-520]]);l.stroked=true;l.filled=false;l.strokeColor=ink;l.strokeWidth=34;l.strokeCap=StrokeCap.ROUNDENDCAP;l.strokeJoin=StrokeJoin.ROUNDENDJOIN;
var l=doc.pathItems.add();l.setEntirePath([[306,-520],[300.8,-446.8]]);l.stroked=true;l.filled=false;l.strokeColor=ink;l.strokeWidth=34;l.strokeCap=StrokeCap.ROUNDENDCAP;l.strokeJoin=StrokeJoin.ROUNDENDJOIN;
var l=doc.pathItems.add();l.setEntirePath([[300.8,-446.8],[299.6,-413.5]]);l.stroked=true;l.filled=false;l.strokeColor=ink;l.strokeWidth=34;l.strokeCap=StrokeCap.ROUNDENDCAP;l.strokeJoin=StrokeJoin.ROUNDENDJOIN;
var l=doc.pathItems.add();l.setEntirePath([[526,-461.5],[568.9,-447]]);l.stroked=true;l.filled=false;l.strokeColor=ink;l.strokeWidth=34;l.strokeCap=StrokeCap.ROUNDENDCAP;l.strokeJoin=StrokeJoin.ROUNDENDJOIN;
var l=doc.pathItems.add();l.setEntirePath([[568.9,-447],[466.8,-429.5]]);l.stroked=true;l.filled=false;l.strokeColor=ink;l.strokeWidth=34;l.strokeCap=StrokeCap.ROUNDENDCAP;l.strokeJoin=StrokeJoin.ROUNDENDJOIN;
var l=doc.pathItems.add();l.setEntirePath([[466.8,-429.5],[478.3,-398.7]]);l.stroked=true;l.filled=false;l.strokeColor=ink;l.strokeWidth=34;l.strokeCap=StrokeCap.ROUNDENDCAP;l.strokeJoin=StrokeJoin.ROUNDENDJOIN;
var l=doc.pathItems.add();l.setEntirePath([[407,-437.7],[328.9,-372.5]]);l.stroked=true;l.filled=false;l.strokeColor=ink;l.strokeWidth=34;l.strokeCap=StrokeCap.ROUNDENDCAP;l.strokeJoin=StrokeJoin.ROUNDENDJOIN;
var l=doc.pathItems.add();l.setEntirePath([[407,-437.7],[408.6,-374.3]]);l.stroked=true;l.filled=false;l.strokeColor=ink;l.strokeWidth=34;l.strokeCap=StrokeCap.ROUNDENDCAP;l.strokeJoin=StrokeJoin.ROUNDENDJOIN;
var l=doc.pathItems.add();l.setEntirePath([[328.9,-372.5],[220.9,-233.5]]);l.stroked=true;l.filled=false;l.strokeColor=ink;l.strokeWidth=34;l.strokeCap=StrokeCap.ROUNDENDCAP;l.strokeJoin=StrokeJoin.ROUNDENDJOIN;
var l=doc.pathItems.add();l.setEntirePath([[220.9,-233.5],[289.5,-175.1]]);l.stroked=true;l.filled=false;l.strokeColor=ink;l.strokeWidth=34;l.strokeCap=StrokeCap.ROUNDENDCAP;l.strokeJoin=StrokeJoin.ROUNDENDJOIN;
var l=doc.pathItems.add();l.setEntirePath([[289.5,-175.1],[274.2,-125.1]]);l.stroked=true;l.filled=false;l.strokeColor=ink;l.strokeWidth=34;l.strokeCap=StrokeCap.ROUNDENDCAP;l.strokeJoin=StrokeJoin.ROUNDENDJOIN;
var l=doc.pathItems.add();l.setEntirePath([[408.6,-374.3],[388.8,-199.3]]);l.stroked=true;l.filled=false;l.strokeColor=ink;l.strokeWidth=34;l.strokeCap=StrokeCap.ROUNDENDCAP;l.strokeJoin=StrokeJoin.ROUNDENDJOIN;
var l=doc.pathItems.add();l.setEntirePath([[388.8,-199.3],[240.4,-140.7]]);l.stroked=true;l.filled=false;l.strokeColor=ink;l.strokeWidth=34;l.strokeCap=StrokeCap.ROUNDENDCAP;l.strokeJoin=StrokeJoin.ROUNDENDJOIN;
var l=doc.pathItems.add();l.setEntirePath([[240.4,-140.7],[204.7,-80]]);l.stroked=true;l.filled=false;l.strokeColor=ink;l.strokeWidth=34;l.strokeCap=StrokeCap.ROUNDENDCAP;l.strokeJoin=StrokeJoin.ROUNDENDJOIN;
var h=doc.pathItems.ellipse(-411.9,462,74,74);h.stroked=false;h.filled=true;h.fillColor=ink;

var l=doc.pathItems.add();l.setEntirePath([[406.7,-192.8],[382.2,-213.5]]);l.stroked=true;l.filled=false;l.strokeColor=paper;l.strokeWidth=44;l.strokeCap=StrokeCap.ROUNDENDCAP;l.strokeJoin=StrokeJoin.ROUNDENDJOIN;
var l=doc.pathItems.add();l.setEntirePath([[382.2,-213.5],[314.1,-198.5]]);l.stroked=true;l.filled=false;l.strokeColor=paper;l.strokeWidth=44;l.strokeCap=StrokeCap.ROUNDENDCAP;l.strokeJoin=StrokeJoin.ROUNDENDJOIN;
var l=doc.pathItems.add();l.setEntirePath([[382.2,-213.5],[437.6,-207.9]]);l.stroked=true;l.filled=false;l.strokeColor=paper;l.strokeWidth=44;l.strokeCap=StrokeCap.ROUNDENDCAP;l.strokeJoin=StrokeJoin.ROUNDENDJOIN;
var l=doc.pathItems.add();l.setEntirePath([[382.2,-213.5],[320.5,-242.2]]);l.stroked=true;l.filled=false;l.strokeColor=paper;l.strokeWidth=44;l.strokeCap=StrokeCap.ROUNDENDCAP;l.strokeJoin=StrokeJoin.ROUNDENDJOIN;
var l=doc.pathItems.add();l.setEntirePath([[437.6,-207.9],[455.7,-324.4]]);l.stroked=true;l.filled=false;l.strokeColor=paper;l.strokeWidth=44;l.strokeCap=StrokeCap.ROUNDENDCAP;l.strokeJoin=StrokeJoin.ROUNDENDJOIN;
var l=doc.pathItems.add();l.setEntirePath([[455.7,-324.4],[436.6,-390.5]]);l.stroked=true;l.filled=false;l.strokeColor=paper;l.strokeWidth=44;l.strokeCap=StrokeCap.ROUNDENDCAP;l.strokeJoin=StrokeJoin.ROUNDENDJOIN;
var l=doc.pathItems.add();l.setEntirePath([[436.6,-390.5],[438.6,-378.8]]);l.stroked=true;l.filled=false;l.strokeColor=paper;l.strokeWidth=44;l.strokeCap=StrokeCap.ROUNDENDCAP;l.strokeJoin=StrokeJoin.ROUNDENDJOIN;
var l=doc.pathItems.add();l.setEntirePath([[320.5,-242.2],[301.9,-361.8]]);l.stroked=true;l.filled=false;l.strokeColor=paper;l.strokeWidth=44;l.strokeCap=StrokeCap.ROUNDENDCAP;l.strokeJoin=StrokeJoin.ROUNDENDJOIN;
var l=doc.pathItems.add();l.setEntirePath([[301.9,-361.8],[397.8,-399.5]]);l.stroked=true;l.filled=false;l.strokeColor=paper;l.strokeWidth=44;l.strokeCap=StrokeCap.ROUNDENDCAP;l.strokeJoin=StrokeJoin.ROUNDENDJOIN;
var l=doc.pathItems.add();l.setEntirePath([[397.8,-399.5],[406.8,-395.2]]);l.stroked=true;l.filled=false;l.strokeColor=paper;l.strokeWidth=44;l.strokeCap=StrokeCap.ROUNDENDCAP;l.strokeJoin=StrokeJoin.ROUNDENDJOIN;
var l=doc.pathItems.add();l.setEntirePath([[314.1,-198.5],[336.3,-258.3]]);l.stroked=true;l.filled=false;l.strokeColor=paper;l.strokeWidth=44;l.strokeCap=StrokeCap.ROUNDENDCAP;l.strokeJoin=StrokeJoin.ROUNDENDJOIN;
var l=doc.pathItems.add();l.setEntirePath([[314.1,-198.5],[256.7,-282.9]]);l.stroked=true;l.filled=false;l.strokeColor=paper;l.strokeWidth=44;l.strokeCap=StrokeCap.ROUNDENDCAP;l.strokeJoin=StrokeJoin.ROUNDENDJOIN;
var l=doc.pathItems.add();l.setEntirePath([[336.3,-258.3],[467,-372.4]]);l.stroked=true;l.filled=false;l.strokeColor=paper;l.strokeWidth=44;l.strokeCap=StrokeCap.ROUNDENDCAP;l.strokeJoin=StrokeJoin.ROUNDENDJOIN;
var l=doc.pathItems.add();l.setEntirePath([[467,-372.4],[356.2,-312.1]]);l.stroked=true;l.filled=false;l.strokeColor=paper;l.strokeWidth=44;l.strokeCap=StrokeCap.ROUNDENDCAP;l.strokeJoin=StrokeJoin.ROUNDENDJOIN;
var l=doc.pathItems.add();l.setEntirePath([[356.2,-312.1],[314.5,-298.4]]);l.stroked=true;l.filled=false;l.strokeColor=paper;l.strokeWidth=44;l.strokeCap=StrokeCap.ROUNDENDCAP;l.strokeJoin=StrokeJoin.ROUNDENDJOIN;
var l=doc.pathItems.add();l.setEntirePath([[256.7,-282.9],[253.8,-435.1]]);l.stroked=true;l.filled=false;l.strokeColor=paper;l.strokeWidth=44;l.strokeCap=StrokeCap.ROUNDENDCAP;l.strokeJoin=StrokeJoin.ROUNDENDJOIN;
var l=doc.pathItems.add();l.setEntirePath([[253.8,-435.1],[208.8,-337]]);l.stroked=true;l.filled=false;l.strokeColor=paper;l.strokeWidth=44;l.strokeCap=StrokeCap.ROUNDENDCAP;l.strokeJoin=StrokeJoin.ROUNDENDJOIN;
var l=doc.pathItems.add();l.setEntirePath([[208.8,-337],[191.1,-333.6]]);l.stroked=true;l.filled=false;l.strokeColor=paper;l.strokeWidth=44;l.strokeCap=StrokeCap.ROUNDENDCAP;l.strokeJoin=StrokeJoin.ROUNDENDJOIN;
var h=doc.pathItems.ellipse(-150.8,364.7,84,84);h.stroked=false;h.filled=true;h.fillColor=paper;

var tq=doc.pathItems.add();tq.setEntirePath([[437.6,-207.9],[320.5,-242.2],[256.7,-282.9],[336.3,-258.3]]);tq.closed=true;tq.stroked=false;tq.filled=true;tq.fillColor=clay;
var l=doc.pathItems.add();l.setEntirePath([[406.7,-192.8],[382.2,-213.5]]);l.stroked=true;l.filled=false;l.strokeColor=clay;l.strokeWidth=34;l.strokeCap=StrokeCap.ROUNDENDCAP;l.strokeJoin=StrokeJoin.ROUNDENDJOIN;
var l=doc.pathItems.add();l.setEntirePath([[382.2,-213.5],[314.1,-198.5]]);l.stroked=true;l.filled=false;l.strokeColor=clay;l.strokeWidth=34;l.strokeCap=StrokeCap.ROUNDENDCAP;l.strokeJoin=StrokeJoin.ROUNDENDJOIN;
var l=doc.pathItems.add();l.setEntirePath([[382.2,-213.5],[437.6,-207.9]]);l.stroked=true;l.filled=false;l.strokeColor=clay;l.strokeWidth=34;l.strokeCap=StrokeCap.ROUNDENDCAP;l.strokeJoin=StrokeJoin.ROUNDENDJOIN;
var l=doc.pathItems.add();l.setEntirePath([[382.2,-213.5],[320.5,-242.2]]);l.stroked=true;l.filled=false;l.strokeColor=clay;l.strokeWidth=34;l.strokeCap=StrokeCap.ROUNDENDCAP;l.strokeJoin=StrokeJoin.ROUNDENDJOIN;
var l=doc.pathItems.add();l.setEntirePath([[437.6,-207.9],[455.7,-324.4]]);l.stroked=true;l.filled=false;l.strokeColor=clay;l.strokeWidth=34;l.strokeCap=StrokeCap.ROUNDENDCAP;l.strokeJoin=StrokeJoin.ROUNDENDJOIN;
var l=doc.pathItems.add();l.setEntirePath([[455.7,-324.4],[436.6,-390.5]]);l.stroked=true;l.filled=false;l.strokeColor=clay;l.strokeWidth=34;l.strokeCap=StrokeCap.ROUNDENDCAP;l.strokeJoin=StrokeJoin.ROUNDENDJOIN;
var l=doc.pathItems.add();l.setEntirePath([[436.6,-390.5],[438.6,-378.8]]);l.stroked=true;l.filled=false;l.strokeColor=clay;l.strokeWidth=34;l.strokeCap=StrokeCap.ROUNDENDCAP;l.strokeJoin=StrokeJoin.ROUNDENDJOIN;
var l=doc.pathItems.add();l.setEntirePath([[320.5,-242.2],[301.9,-361.8]]);l.stroked=true;l.filled=false;l.strokeColor=clay;l.strokeWidth=34;l.strokeCap=StrokeCap.ROUNDENDCAP;l.strokeJoin=StrokeJoin.ROUNDENDJOIN;
var l=doc.pathItems.add();l.setEntirePath([[301.9,-361.8],[397.8,-399.5]]);l.stroked=true;l.filled=false;l.strokeColor=clay;l.strokeWidth=34;l.strokeCap=StrokeCap.ROUNDENDCAP;l.strokeJoin=StrokeJoin.ROUNDENDJOIN;
var l=doc.pathItems.add();l.setEntirePath([[397.8,-399.5],[406.8,-395.2]]);l.stroked=true;l.filled=false;l.strokeColor=clay;l.strokeWidth=34;l.strokeCap=StrokeCap.ROUNDENDCAP;l.strokeJoin=StrokeJoin.ROUNDENDJOIN;
var l=doc.pathItems.add();l.setEntirePath([[314.1,-198.5],[336.3,-258.3]]);l.stroked=true;l.filled=false;l.strokeColor=clay;l.strokeWidth=34;l.strokeCap=StrokeCap.ROUNDENDCAP;l.strokeJoin=StrokeJoin.ROUNDENDJOIN;
var l=doc.pathItems.add();l.setEntirePath([[314.1,-198.5],[256.7,-282.9]]);l.stroked=true;l.filled=false;l.strokeColor=clay;l.strokeWidth=34;l.strokeCap=StrokeCap.ROUNDENDCAP;l.strokeJoin=StrokeJoin.ROUNDENDJOIN;
var l=doc.pathItems.add();l.setEntirePath([[336.3,-258.3],[467,-372.4]]);l.stroked=true;l.filled=false;l.strokeColor=clay;l.strokeWidth=34;l.strokeCap=StrokeCap.ROUNDENDCAP;l.strokeJoin=StrokeJoin.ROUNDENDJOIN;
var l=doc.pathItems.add();l.setEntirePath([[467,-372.4],[356.2,-312.1]]);l.stroked=true;l.filled=false;l.strokeColor=clay;l.strokeWidth=34;l.strokeCap=StrokeCap.ROUNDENDCAP;l.strokeJoin=StrokeJoin.ROUNDENDJOIN;
var l=doc.pathItems.add();l.setEntirePath([[356.2,-312.1],[314.5,-298.4]]);l.stroked=true;l.filled=false;l.strokeColor=clay;l.strokeWidth=34;l.strokeCap=StrokeCap.ROUNDENDCAP;l.strokeJoin=StrokeJoin.ROUNDENDJOIN;
var l=doc.pathItems.add();l.setEntirePath([[256.7,-282.9],[253.8,-435.1]]);l.stroked=true;l.filled=false;l.strokeColor=clay;l.strokeWidth=34;l.strokeCap=StrokeCap.ROUNDENDCAP;l.strokeJoin=StrokeJoin.ROUNDENDJOIN;
var l=doc.pathItems.add();l.setEntirePath([[253.8,-435.1],[208.8,-337]]);l.stroked=true;l.filled=false;l.strokeColor=clay;l.strokeWidth=34;l.strokeCap=StrokeCap.ROUNDENDCAP;l.strokeJoin=StrokeJoin.ROUNDENDJOIN;
var l=doc.pathItems.add();l.setEntirePath([[208.8,-337],[191.1,-333.6]]);l.stroked=true;l.filled=false;l.strokeColor=clay;l.strokeWidth=34;l.strokeCap=StrokeCap.ROUNDENDCAP;l.strokeJoin=StrokeJoin.ROUNDENDJOIN;
var h=doc.pathItems.ellipse(-155.8,369.7,74,74);h.stroked=false;h.filled=true;h.fillColor=clay;

var f=new File(OUT);var opt=new ExportOptionsPNG24();opt.transparency=true;opt.artBoardClipping=true;
doc.exportFile(f, ExportType.PNG24, opt);doc.close(SaveOptions.DONOTSAVECHANGES);
"exists="+f.exists;
}catch(e){"ERR:"+e.toString();}