// THROWAWAY multi-POV extractor (Phase 5). Reuses the SAME selection logic as
// extract_batch.test.ts (concept buckets + pickClearestVariant) but restricted to
// the ~6 highest-legibility closed-guard-neighbourhood concepts, and emits the
// TESTED camerasFor(pose, 4) (4 orbiting cameras) per pose instead of a single
// cameraFor. Output: Blender-ready multipov_data.py with a BATCH of {slug,name,
// concept,top,pose,cams:[{eye,target},x4]}.
import { readFileSync, writeFileSync } from "node:fs";
import { test } from "vitest";
import { parseGrappleMap, JOINTS, type Pose, type GMPosition } from "../../src/lib/grapplemap/parser";
import { closedGuardNeighbourhood } from "../../src/lib/grapplemap/bjj-filter";
import { camerasFor, legibilityScore, pickClearestVariant } from "../../src/lib/grapplemap/render-spec";

const txt = readFileSync("source_repos/GrappleMap/GrappleMap.txt", "utf8");
const PY = ".scratch/figuras-grapplemap-pipeline/multipov_data.py";

function slugify(name: string): string {
  return name
    .toLowerCase()
    .replace(/\\n/g, " ")
    .normalize("NFD")
    .replace(/[̀-ͯ]/g, "")
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "")
    .slice(0, 48);
}

// GM (x,y,z) -> Blender (x, z, y)
function poseToPyDict(pose: Pose): string {
  const fmt = (player: 0 | 1): string =>
    JOINTS.map((j, i) => {
      const v = pose[player][i];
      return `        '${j}': (${v.x.toFixed(3)}, ${v.z.toFixed(3)}, ${v.y.toFixed(3)}),`;
    }).join("\n");
  return `{\n    'p0': {\n${fmt(0)}\n    },\n    'p1': {\n${fmt(1)}\n    },\n}`;
}

test("extract multipov", () => {
  const data = parseGrappleMap(txt);
  const nbh = closedGuardNeighbourhood(data, { hops: 3 });

  type Concept = { key: string; nome: string; match: (p: GMPosition) => boolean };
  const hasTag = (p: GMPosition, t: string) => p.tags.includes(t);
  const nm = (p: GMPosition, re: RegExp) => re.test(p.name);
  // The 6 highest-legibility neighbourhood concepts (per Phase 4 read).
  const concepts: Concept[] = [
    { key: "closed_guard", nome: "Guarda fechada", match: (p) => hasTag(p, "closed_guard") && nm(p, /closed guard|full guard/i) },
    { key: "mount", nome: "Montada", match: (p) => hasTag(p, "mount") && nm(p, /mount/i) && !nm(p, /half|s-mount|technical/i) },
    { key: "knee_on_belly", nome: "Joelho na barriga", match: (p) => hasTag(p, "knee_on_belly") || nm(p, /knee on belly|knee.?on.?belly/i) },
    { key: "north_south", nome: "Norte-sul", match: (p) => hasTag(p, "north_south") || nm(p, /north.?south/i) },
    { key: "triangle", nome: "Triângulo", match: (p) => hasTag(p, "triangle") && nm(p, /triangle/i) && !nm(p, /arm.?triangle/i) },
    { key: "back_control", nome: "Pelas costas", match: (p) => hasTag(p, "back") && nm(p, /back control|back mount|rear/i) },
  ];

  const pool = data.positions;
  const inNbh = new Set(nbh.positions.map((p) => p.id));
  const usedIds = new Set<number>();
  const picked: { concept: string; nome: string; pos: GMPosition }[] = [];

  for (const c of concepts) {
    const variants = pool.filter((p) => c.match(p));
    if (variants.length === 0) continue;
    const best = pickClearestVariant(variants.map((p) => ({ id: p.id, pose: p.pose })));
    const chosen = variants.find((p) => p.id === best.id)!;
    if (usedIds.has(chosen.id)) continue;
    usedIds.add(chosen.id);
    picked.push({ concept: c.key, nome: c.nome, pos: chosen });
  }

  const bx = (v: { x: number; y: number; z: number }) =>
    `(${v.x.toFixed(4)}, ${v.z.toFixed(4)}, ${v.y.toFixed(4)})`;

  let py = `# AUTO-GENERATED by extract_multipov.test.ts (Phase 5 multi-POV).\n`;
  py += `# Cams come from camerasFor(pose, 4): 4 deterministic orbiting cameras,\n`;
  py += `# cams[0] = primary (cameraFor). eye/target remapped GM y-up -> Blender z-up (x,z,y).\n`;
  py += `BATCH = [\n`;
  for (const { concept, nome, pos } of picked) {
    const slug = slugify(pos.name) || `pos-${pos.id}`;
    const cams = camerasFor(pos.pose, 4);
    const topIsP0 = pos.pose[0][JOINTS.indexOf("Head")].y > pos.pose[1][JOINTS.indexOf("Head")].y;
    py += `  {\n`;
    py += `    'id': ${pos.id}, 'slug': ${JSON.stringify(slug)},\n`;
    py += `    'name': ${JSON.stringify(pos.name.replace(/\\n/g, " "))}, 'concept': ${JSON.stringify(concept)},\n`;
    py += `    'nome': ${JSON.stringify(nome)},\n`;
    py += `    'top': ${topIsP0 ? "'p0'" : "'p1'"},\n`;
    py += `    'cams': [\n`;
    for (const cam of cams) {
      py += `      {'eye': ${bx(cam.eye)}, 'target': ${bx(cam.target)}},\n`;
    }
    py += `    ],\n`;
    py += `    'pose': ${poseToPyDict(pos.pose).replace(/\n/g, "\n    ")},\n`;
    py += `  },\n`;
  }
  py += `]\n`;
  writeFileSync(PY, py);
  console.log(`wrote ${PY} with ${picked.length} positions`);
  for (const p of picked) console.log(`  ${p.concept} -> [${p.pos.id}] ${p.pos.name.replace(/\\n/g, " ")} (legib=${legibilityScore(p.pos.pose).toFixed(2)})`);
});
